package agentsdk

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"mime"
	"strings"

	"github.com/airlockrun/goai"
	"github.com/airlockrun/goai/model"
)

// mediaResult is the JS-facing return value for generateImage / speak.
// The S3 key is what the LLM uses next (printToUser, attachToContext).
type mediaResult struct {
	Key      string `json:"key"`
	MimeType string `json:"mimeType"`
	Size     int    `json:"size"`
}

// transcribeAudio loads bytes from agent storage at `key`, runs them through
// the system-default transcription model, and returns the goai result. The
// model is resolved server-side by capability — JS callers don't pick a slug.
func (r *run) transcribeAudio(ctx context.Context, key string, opts model.TranscribeCallOptions) (*goai.TranscriptionResult, error) {
	zone, relKey, ok := r.agent.findStorageByKey(key)
	if !ok {
		return nil, fmt.Errorf("transcribeAudio: %q must be a {storage}/{key} path under a registered zone", key)
	}
	rc, err := zone.Get(ctx, relKey)
	if err != nil {
		return nil, fmt.Errorf("load %s: %w", key, err)
	}
	defer rc.Close()
	audio, err := io.ReadAll(rc)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", key, err)
	}

	if info, err := zone.Stat(ctx, relKey); err == nil && opts.MimeType == "" {
		opts.MimeType = info.ContentType
	}

	stt := r.agent.TranscriptionModel(ctx, "", ModelOpts{Capability: CapTranscription})
	return goai.Transcribe(ctx, goai.TranscribeInput{
		Model:           stt,
		Audio:           audio,
		MimeType:        opts.MimeType,
		Filename:        opts.Filename,
		Language:        opts.Language,
		Prompt:          opts.Prompt,
		ProviderOptions: opts.ProviderOptions,
	})
}

// generateImage runs the prompt through the system-default image model and
// writes the first generated image to agent storage at `saveAs` (auto-named
// when empty). Returns the key + metadata for downstream printToUser /
// attachToContext calls.
func (r *run) generateImage(ctx context.Context, prompt, saveAs string, opts model.ImageCallOptions) (*mediaResult, error) {
	m := r.agent.ImageModel(ctx, "", ModelOpts{Capability: CapImage})
	res, err := goai.GenerateImage(ctx, goai.ImageInput{
		Model:           m,
		Prompt:          prompt,
		N:               1,
		Size:            opts.Size,
		AspectRatio:     opts.AspectRatio,
		Seed:            opts.Seed,
		ProviderOptions: opts.ProviderOptions,
	})
	if err != nil {
		return nil, err
	}
	if len(res.Images) == 0 {
		return nil, fmt.Errorf("model returned no images")
	}
	img := res.Images[0]
	if img.Base64 == "" {
		return nil, fmt.Errorf("image returned without inline data (URL-only responses not supported)")
	}
	data, err := decodeBase64(img.Base64)
	if err != nil {
		return nil, fmt.Errorf("decode image: %w", err)
	}
	return r.storeMediaResult(ctx, "image", saveAs, data, img.MimeType)
}

// generateSpeech runs `text` through the system-default TTS model and writes
// the audio bytes to agent storage at `saveAs` (auto-named when empty).
func (r *run) generateSpeech(ctx context.Context, text, saveAs string, opts model.SpeechCallOptions) (*mediaResult, error) {
	m := r.agent.SpeechModel(ctx, "", ModelOpts{Capability: CapSpeech})
	res, err := goai.GenerateSpeech(ctx, goai.SpeechInput{
		Model:           m,
		Text:            text,
		Voice:           opts.Voice,
		OutputFormat:    opts.OutputFormat,
		Speed:           opts.Speed,
		ProviderOptions: opts.ProviderOptions,
	})
	if err != nil {
		return nil, err
	}
	if len(res.Audio) == 0 {
		return nil, fmt.Errorf("model returned no audio")
	}
	return r.storeMediaResult(ctx, "speech", saveAs, res.Audio, res.MimeType)
}

// embed proxies the embedding call through Airlock. Texts are small enough
// that the inline-bytes round-trip is fine.
func (r *run) embed(ctx context.Context, texts []string) ([][]float64, error) {
	m := r.agent.EmbeddingModel(ctx, "", ModelOpts{Capability: CapEmbedding})
	res, err := goai.Embed(ctx, goai.EmbedInput{
		Model:  m,
		Values: texts,
	})
	if err != nil {
		return nil, err
	}
	out := make([][]float64, len(res.Embeddings))
	for i, e := range res.Embeddings {
		out[i] = e.Values
	}
	return out, nil
}

// storeMediaResult writes generated bytes to a registered storage zone and
// returns a JS-facing result. When `saveAs` is empty we auto-generate a key
// under the framework-owned tmp zone (same convention as truncated tool
// outputs in tools.go). When provided, `saveAs` must be in "{zone}/{key}"
// form referring to a registered zone. When the model doesn't supply a
// MIME type we fall back to a sensible default per category.
func (r *run) storeMediaResult(ctx context.Context, category, saveAs string, data []byte, mimeType string) (*mediaResult, error) {
	if mimeType == "" {
		mimeType = defaultMimeForCategory(category)
	}
	var zone *StorageHandle
	var relKey string
	if saveAs == "" {
		saveAs = reservedTmpSlug + "/generated/" + category + "-" + randomHex(4) + extForMime(mimeType, category)
		zone = &StorageHandle{slug: reservedTmpSlug, read: AccessUser, write: AccessUser, agent: r.agent}
		relKey = strings.TrimPrefix(saveAs, reservedTmpSlug+"/")
	} else {
		var ok bool
		zone, relKey, ok = r.agent.findStorageByKey(saveAs)
		if !ok {
			return nil, fmt.Errorf("storeMediaResult: %q must be a {storage}/{key} path under a registered zone", saveAs)
		}
	}
	if err := zone.Put(ctx, relKey, bytes.NewReader(data), mimeType); err != nil {
		return nil, fmt.Errorf("store %s: %w", saveAs, err)
	}
	return &mediaResult{Key: saveAs, MimeType: mimeType, Size: len(data)}, nil
}

func defaultMimeForCategory(category string) string {
	switch category {
	case "image":
		return "image/png"
	case "speech":
		return "audio/mpeg"
	}
	return "application/octet-stream"
}

func extForMime(mimeType, category string) string {
	if exts, _ := mime.ExtensionsByType(mimeType); len(exts) > 0 {
		return exts[0]
	}
	switch category {
	case "image":
		return ".png"
	case "speech":
		return ".mp3"
	}
	return ".bin"
}

func decodeBase64(s string) ([]byte, error) {
	return base64.StdEncoding.DecodeString(s)
}
