package agentsdk

import (
	"context"
	"encoding/json"
	"strings"
	"testing"
)

// Media bindings register on every VM. Each test verifies that the JS call
// produces the right wire requests against the mock Airlock — the actual
// transcription/generation is exercised by provider_test.go.

func TestTranscribeAudioBinding(t *testing.T) {
	a, mock := testAgent(t)
	a.RegisterStorage(&Storage{Slug: "uploads", Access: AccessUser})
	run := newRun(a, "run-1", "", "", context.Background())

	out, err := executeJS(run.vmRuntime(), `transcribeAudio("uploads/voice.ogg", { language: "en", prompt: "meeting" })`)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, `"text": "mock transcription"`) {
		t.Fatalf("expected text in result, got %s", out)
	}

	// Storage GET pulls the bytes from the agent's S3 bucket.
	if got := mock.RequestsByPath("/api/agent/storage/uploads/voice.ogg"); len(got) == 0 {
		t.Fatal("expected GET to /api/agent/storage/uploads/voice.ogg")
	}

	// Then transcription proxy is invoked with the bytes inline.
	reqs := mock.RequestsByPath("/api/agent/llm/transcription")
	if len(reqs) != 1 {
		t.Fatalf("expected 1 transcription request, got %d", len(reqs))
	}
	var body struct {
		Capability string          `json:"capability"`
		Slug       string          `json:"slug"`
		Options    json.RawMessage `json:"options"`
	}
	if err := json.Unmarshal(reqs[0].Body, &body); err != nil {
		t.Fatal(err)
	}
	if body.Capability != "transcription" {
		t.Errorf("capability = %q, want transcription", body.Capability)
	}
	if body.Slug != "" {
		t.Errorf("slug should be empty for capability-routed call, got %q", body.Slug)
	}
	var opts struct {
		Audio    []byte `json:"audio"`
		Language string `json:"language"`
		Prompt   string `json:"prompt"`
	}
	if err := json.Unmarshal(body.Options, &opts); err != nil {
		t.Fatal(err)
	}
	if string(opts.Audio) != "mock-file-content" {
		t.Errorf("audio = %q, want bytes from storage GET", string(opts.Audio))
	}
	if opts.Language != "en" {
		t.Errorf("language = %q, want en", opts.Language)
	}
	if opts.Prompt != "meeting" {
		t.Errorf("prompt = %q, want meeting", opts.Prompt)
	}
}

func TestGenerateImageBinding(t *testing.T) {
	a, mock := testAgent(t)
	a.RegisterStorage(&Storage{Slug: "uploads", Access: AccessUser})
	run := newRun(a, "run-1", "", "", context.Background())

	out, err := executeJS(run.vmRuntime(), `generateImage("a sunset", { saveAs: "uploads/out.png", size: "1024x1024" })`)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, `"key": "uploads/out.png"`) {
		t.Fatalf("expected key in result, got %s", out)
	}
	if !strings.Contains(out, `"mimeType": "image/png"`) {
		t.Fatalf("expected mimeType in result, got %s", out)
	}

	// Image proxy invocation.
	reqs := mock.RequestsByPath("/api/agent/llm/image")
	if len(reqs) != 1 {
		t.Fatalf("expected 1 image request, got %d", len(reqs))
	}
	var body struct {
		Capability string          `json:"capability"`
		Options    json.RawMessage `json:"options"`
	}
	json.Unmarshal(reqs[0].Body, &body)
	if body.Capability != "image" {
		t.Errorf("capability = %q, want image", body.Capability)
	}

	// Generated bytes were written back to agent storage at saveAs (zone-prefixed).
	if got := mock.RequestsByPath("/api/agent/storage/uploads/out.png"); len(got) == 0 {
		t.Fatal("expected PUT to /api/agent/storage/uploads/out.png")
	}
}

func TestGenerateImageAutoKey(t *testing.T) {
	a, mock := testAgent(t)
	run := newRun(a, "run-1", "", "", context.Background())

	out, err := executeJS(run.vmRuntime(), `generateImage("a cat")`)
	if err != nil {
		t.Fatal(err)
	}
	// Auto-generated key lives in the framework's tmp zone.
	if !strings.Contains(out, `"key": "tmp/generated/image-`) {
		t.Fatalf("expected auto key under tmp/generated/, got %s", out)
	}
	storagePuts := mock.RequestsByPath("/api/agent/storage/tmp/generated/image-")
	if len(storagePuts) == 0 {
		t.Fatal("expected PUT under tmp/generated/")
	}
}

func TestSpeakBinding(t *testing.T) {
	a, mock := testAgent(t)
	a.RegisterStorage(&Storage{Slug: "uploads", Access: AccessUser})
	run := newRun(a, "run-1", "", "", context.Background())

	out, err := executeJS(run.vmRuntime(), `speak("hello world", { saveAs: "uploads/voice.mp3", voice: "alloy" })`)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, `"key": "uploads/voice.mp3"`) {
		t.Fatalf("expected key in result, got %s", out)
	}

	reqs := mock.RequestsByPath("/api/agent/llm/speech")
	if len(reqs) != 1 {
		t.Fatalf("expected 1 speech request, got %d", len(reqs))
	}
	var body struct {
		Capability string `json:"capability"`
	}
	json.Unmarshal(reqs[0].Body, &body)
	if body.Capability != "speech" {
		t.Errorf("capability = %q, want speech", body.Capability)
	}

	if got := mock.RequestsByPath("/api/agent/storage/uploads/voice.mp3"); len(got) == 0 {
		t.Fatal("expected PUT to /api/agent/storage/uploads/voice.mp3")
	}
}

func TestEmbedBinding(t *testing.T) {
	a, mock := testAgent(t)
	run := newRun(a, "run-1", "", "", context.Background())

	out, err := executeJS(run.vmRuntime(), `embed(["hello", "world"])`)
	if err != nil {
		t.Fatal(err)
	}
	// Mock returns one embedding per call regardless of input length, so we
	// just check the shape — outer array, inner numbers.
	if !strings.Contains(out, "0.1") || !strings.Contains(out, "0.2") {
		t.Fatalf("expected embedding values in result, got %s", out)
	}

	reqs := mock.RequestsByPath("/api/agent/llm/embedding")
	if len(reqs) != 1 {
		t.Fatalf("expected 1 embedding request, got %d", len(reqs))
	}
	var body struct {
		Capability string          `json:"capability"`
		Options    json.RawMessage `json:"options"`
	}
	json.Unmarshal(reqs[0].Body, &body)
	if body.Capability != "embedding" {
		t.Errorf("capability = %q, want embedding", body.Capability)
	}
	var opts struct {
		Values []string `json:"values"`
	}
	json.Unmarshal(body.Options, &opts)
	if len(opts.Values) != 2 || opts.Values[0] != "hello" || opts.Values[1] != "world" {
		t.Errorf("values = %v, want [hello world]", opts.Values)
	}
}

func TestEmbedAcceptsString(t *testing.T) {
	a, mock := testAgent(t)
	run := newRun(a, "run-1", "", "", context.Background())

	if _, err := executeJS(run.vmRuntime(), `embed("just one")`); err != nil {
		t.Fatal(err)
	}
	reqs := mock.RequestsByPath("/api/agent/llm/embedding")
	if len(reqs) != 1 {
		t.Fatalf("expected 1 request, got %d", len(reqs))
	}
	var body struct {
		Options json.RawMessage `json:"options"`
	}
	json.Unmarshal(reqs[0].Body, &body)
	var opts struct {
		Values []string `json:"values"`
	}
	json.Unmarshal(body.Options, &opts)
	if len(opts.Values) != 1 || opts.Values[0] != "just one" {
		t.Errorf("values = %v, want [just one]", opts.Values)
	}
}
