#!/usr/bin/env bash
# Regenerate the baseline third-party notices materialized into every agent.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/scaffold/templates/THIRD_PARTY_NOTICES.generated.md"
modules=$(mktemp)
trap 'rm -f "$modules"' EXIT

mit_block() {
	cat <<EOF
================================================================================
$1 $2
================================================================================
MIT License

Copyright (c) $3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

EOF
}

{
	echo "# Third-Party Notices — airlock agent"
	echo
	echo "Generated by agentsdk/scripts/gen-notices.sh — do not edit by hand."
	echo "Re-run after dependency or pinned-version bumps."
	echo
	echo "This lists the open-source software bundled in the distributed binary"
	echo "and reproduces each component's license (and NOTICE, where required)."
	echo
} >"$OUT"

(
	cd "$ROOT"
	GOWORK=off go list -deps -f '{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}' ./...
) | sort -u | awk -F'|' 'NF==3 && $3!=""' >"$modules"

while IFS='|' read -r path version dir; do
	[ -z "$dir" ] && continue
	license=""
	for candidate in "$dir"/LICENSE* "$dir"/COPYING* "$dir"/LICENCE*; do
		if [ -f "$candidate" ]; then
			license="$candidate"
			break
		fi
	done
	{
		echo "================================================================================"
		echo "$path${version:+ $version}"
		echo "================================================================================"
		if [ -n "$license" ]; then
			cat "$license"
		else
			echo "(no license file found in module source)"
			echo "WARNING: no license file for $path" >&2
		fi
		for notice in "$dir"/NOTICE*; do
			[ -f "$notice" ] || continue
			echo
			echo "--- NOTICE ---"
			cat "$notice"
		done
		echo
		echo
	} >>"$OUT"
done <"$modules"

TAILWIND_VERSION=$(grep -oE 'TailwindVersion = "[^"]+"' "$ROOT/scaffold/versions.go" | grep -oE '"[^"]+"' | tr -d '"')
DAISYUI_VERSION=$(grep -oE 'DaisyUIVersion = "[^"]+"' "$ROOT/scaffold/versions.go" | grep -oE '"[^"]+"' | tr -d '"')
LUCIDE_VERSION=$(grep -m1 -oE 'Version = "[^"]+"' "$ROOT/lucide/lucide.go" | grep -oE '"[^"]+"' | tr -d '"')
{
	echo "The agent's stylesheet is compiled with the following tools; their"
	echo "authored CSS is embedded in the compiled output the agent serves."
	echo
	mit_block "Tailwind CSS" "$TAILWIND_VERSION" "Tailwind Labs, Inc."
	mit_block "DaisyUI" "$DAISYUI_VERSION" "Pouya Saadeghi"
	echo "================================================================================"
	echo "Lucide Icons $LUCIDE_VERSION"
	echo "================================================================================"
	cat "$ROOT/lucide/UPSTREAM_LICENSE"
	echo
} >>"$OUT"

echo "wrote $OUT"
